spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/voting
    username: postgres
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
